### ISSUE TITLE
M1 Report: Product Scope

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#11]
Task ID: #11

Task details: Document down the product scope of our project, such as a brief description of our product and its purpose

Goals of the task: To document down in the report the scope of the product

Success criteria: When the product scope has been successfully documented in the report

Allocated time: 20 minutes

Start date: 09 September 2023

End date: 09 September 2023

Priority: Medium

**Comment by erickmh859** [comment]
1. Work done in detail: Document down the product scope by including the scope and boundaries of the software, its purpose and benefits of the software.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the product scope is not documented down, the report would not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 09 September 2023
End Date: 09 September 2023

**Comment by chariseeyip** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed! Thanks :D

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed
