### ISSUE TITLE
M1 Report: Related Background Literature

### ISSUE THREAD

**Issue by erickmh859** [RI0US04/P7-2-SIT-INF2001#12]
Task ID: #12

Task details: Document down the background literature related to our project, such as those relating to aircon retailer

Goals of the task: Ensure we document down in the report the background literature related to the project

Success criteria: When the related background literature has been successfully documented in the report

Allocated time: 2 hours

Start date: 09 September 2023

End date: 09 September 2023

Priority: Medium

**Comment by Wee-Ming** [comment]
1. Work done in detail: Document down the related background literature, by including articles related to other aircon retailer companies in the industry, workload management systems in general and aircon retailer companies that use workload management systems.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the related background literature is not documented down, the report would not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 09 September 2023
End Date: 09 September 2023

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed.

**Comment by chariseeyip** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed! Thanks (ㆆ _ ㆆ)
