### ISSUE TITLE
M1 Report: Intended Audience and Document Overview

### ISSUE THREAD

**Issue by Wee-Ming** [RI0US04/P7-2-SIT-INF2001#13]
Task ID: #13

Task details: Document down the intended audience and document overview of our project, such as the different readers that the report is intended for and the overview of what the report contains. 

Goals of the task: Ensure we document down in the report the intended audience and document overview

Success criteria: When the intended audience and document overview has been successfully documented in the report

Allocated time: 2 hours

Start date: 21 September 2023

End date: 21 September 2023

Priority: Low

**Comment by RI0US04** [comment]
Reviewed ʕノ•ᴥ•ʔノ ︵ ┻━┻

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed.
