### ISSUE TITLE
M1 Report: References and Acknowledgements

### ISSUE THREAD

**Issue by erickmh859** [RI0US04/P7-2-SIT-INF2001#14]
Task ID: #14

Task details: Documenting our references and acknowledgement for our M1 report

Goals of the task: Ensure proper documentation of our references and give our acknowledgements to the school and lecturers who has helped us out during the journey of this report

Success criteria: Once the references and acknowledgements are completed with proper documentation

Allocated time: 2 hours

Start date: 21 September 2023

End date:  21 September 2023

Priority: Low

**Comment by TARZH3N** [comment]
1. Work done in detail: Upon completion of the M1 report, our team will ensure proper credits are given to the documents which we have referenced to. As well as, give our due acknowledgements to the school and professors who has helped us with report.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Should we not finish this section, we cannot submit the M1 report as it may be flagged as blatant plagiarism


4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 21 September 2023
End Date: 21 September 2023

**Comment by chariseeyip** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed
