### ISSUE TITLE
M1 Report: Elicitation Method

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#15]
Task ID: #15

Task details: Documenting our elicitation method

Goals of the task: Ensure proper documentation of our elicitation methods 

Success criteria: Once the documentation of the elicitation methods are completed

Allocated time: 2 hours

Start date: 10 September 2023

End date:  10 September 2023

Priority: Medium

**Comment by erickmh859** [comment]
1. Work done in detail: For this section, we have document our methods of elicitation for the M1 report which is the interview with our clients.


2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Should we not finish this section, we cannot submit the M1 report as it is apart of the requirements for the report.


4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 10 September 2023
End Date: 10 September 2023

**Comment by RI0US04** [comment]
Reviewed ԅ(≖‿≖ԅ)

**Comment by chariseeyip** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed
