### ISSUE TITLE
M1 Report: Product Functionality

### ISSUE THREAD

**Issue by Wee-Ming** [RI0US04/P7-2-SIT-INF2001#16]
Issue Detail
Task ID: #16

Task details: Documenting our product functionality

Goals of the task: Ensure proper documentation of our product functionalities 

Success criteria: Once the documentation of the product functionalities are completed

Allocated time: 5 hours

Start date: 6 September 2023

End date:  8 September 2023

Priority: High

1. Work done in detail: Upon completion of the M1 report, our team developed the high level product functionalities that the system will provide for its users.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Should we not finish this section, we cannot submit the M1 report as it is a critical component of the project to outline the key functionalities of our system.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 6 September 2023
End Date: 8 September 2023

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed ヽ(｀Д´)ﾉ
