### ISSUE TITLE
M1 Report: Assumptions and Dependencies

### ISSUE THREAD

**Issue by erickmh859** [RI0US04/P7-2-SIT-INF2001#17]
Task ID: #17

Task details: Documenting down the assumptions and the dependencies of our M1 project 

Goals of the task: Ensure proper documentation of our elicitation methods 

Success criteria: Once the assumption and dependency are documented

Allocated time: 1 hours

Start date: 7 September 2023

End date:  8 September 2023

Priority: Medium

**Comment by chariseeyip** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed <(^_^)>

**Comment by Wee-Ming** [comment]
Reviewed
