### ISSUE TITLE
1.1 Requirements Specification

### ISSUE THREAD

**Issue by Wee-Ming** [RI0US04/P7-2-SIT-INF2001#18]
Task ID: #18

Task details: Find out all requirements in the sub sections ( Functional, Non-Functional, User Interface Requirements) and the System Architecture Diagram is created.

Goals of the task: Ensure that all requirements and System Architecture Diagram are considered through and detailed. 

Success criteria: When all requirements and System Architecture Diagram are confirmed.

Allocated time: 18 Hours

Start date: 06 September 2023

End date: 13 September 2023

Priority: High

**Comment by chariseeyip** [comment]
1. Work done in detail: Finalized all requirements and System Architecture Diagram.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without the completion of this, we cannot proceed to create the Use Case Diagram and Descriptions according to the timeline. 

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 06 September 2023
End Date: 13 September 2023
