### ISSUE TITLE
1.1.1 Confirm Functional Requirements

### ISSUE THREAD

**Issue by lmaoggrofl** [RI0US04/P7-2-SIT-INF2001#19]
Task ID: #19

Task details: Coming up with the functional requirements that the system must have. 

Goals of the task: Ensure the functional requirements are inline with the client’s needs.

Success criteria: Only when functional requirements is stated clearly and confirmed 

Allocated time: 6 Hours

Start date: 6 September 2023

End date:  7 September 2023

Priority: High

**Comment by chariseeyip** [comment]
1. Work done in detail: Creating functional requirements based on the project brief and meeting minutes with clients. 


2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without properly defining the functional requirements, it will be difficult for the development team and stakeholders to know what the system needs to do and causes confusion. This will push back the completion deadline.


4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 6 September 2023
End Date: 7 September 2023

**Comment by erickmh859** [comment]
FR 5-8 Done

**Comment by lmaoggrofl** [comment]
FR 1-4 Done

**Comment by chariseeyip** [comment]
FR 11.1-16.2 Done

**Comment by Wee-Ming** [comment]
FR 17-20 Done

**Comment by RI0US04** [comment]
Fr 21 - 25 Done
