### ISSUE TITLE
1.1.2 Confirm Non-Functional Requirements

### ISSUE THREAD

**Issue by lmaoggrofl** [RI0US04/P7-2-SIT-INF2001#21]
Task ID: #21

Task details: Coming up with the non-functional requirements that the system must have. 

Goals of the task: Ensure the non-functional requirements are inline with the client’s needs.

Success criteria: Only when non-functional requirements is stated clearly and confirmed 

Allocated time: 6 Hours

Start date: 7 September 2023

End date:  8 September 2023

Priority: High

**Comment by lmaoggrofl** [comment]
1. Work done in detail: Creating non-functional requirements based on the project brief and meeting minutes with clients. This includes the performance, safety and security requirements and other requirements.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without properly defining the non-functional requirements, it will be difficult for the development team and stakeholders to know what other requirements that the system needs and cause confusion. This will push back the completion deadline.


4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 7 September 2023
End Date: 8 September 2023

**Comment by erickmh859** [comment]
NFR6 Done

**Comment by chariseeyip** [comment]
NFR1 Done

**Comment by Wee-Ming** [comment]
NFR3 Done

**Comment by lmaoggrofl** [comment]
NFR4 Done

**Comment by TARZH3N** [comment]
NFR5 Done

**Comment by RI0US04** [comment]
NFR2 Done
