### ISSUE TITLE
1.1.2.1 Confirm Performance Requirements

### ISSUE THREAD

**Issue by lmaoggrofl** [RI0US04/P7-2-SIT-INF2001#23]
Task ID: #23

Task details: Confirmation of performance requirements

Goals of the task: Ensure the performance requirements are inline with the client’s needs

Success criteria: Only when performance requirements is stated clearly and confirmed 

Allocated time: 5 hours

Start date: 7 September 2023

End date:  8 September 2023

Priority: High

**Comment by lmaoggrofl** [comment]
1. Work done in detail: For this section, we confirmed our performance requirements of our project such as response time and scalability.


2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Confirming performance requirements is crucial as it sets the standard for how well the system should perform. Failure to do so may lead to uncertainty as the client needs a clear understanding of the performance expectations.


4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 7 September 2023
End Date: 8 September 2023

**Comment by erickmh859** [comment]
NFR12 Done

**Comment by chariseeyip** [comment]
NFR8 Done

**Comment by RI0US04** [comment]
NFR11 Done

**Comment by Wee-Ming** [comment]
NFR7 Done

**Comment by lmaoggrofl** [comment]
NFR9 Done

**Comment by TARZH3N** [comment]
NFR10 Done
