### ISSUE TITLE
M1 Report: Performance Requirements

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#24]
Task ID: #24

Task details: Documenting down the non-functional requirements of our M1 project 

Goals of the task: Ensure proper documentation of our non-functional requirements of the M1 report

Success criteria: Once the non-functional requirements are documented

Allocated time: 4 hours

Start date: 9 September 2023

End date:  9 September 2023

Priority: High

**Comment by Wee-Ming** [comment]
1. Work done in detail: For this section, we have documented our non-functional requirements of our project such as security and safety implementation. 


2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: The non-functional requirements consist of how well the system should perform and the platform’s quality attributes. Without it, it shows an incomplete picture of the system and it causes the M1 report to be incomplete. Which causes delay in the completion 


4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 9 September 2023
End Date: 9 September 2023

**Comment by RI0US04** [comment]
Reviewed (≧︿≦)

**Comment by erickmh859** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed
