### ISSUE TITLE
M1 Report: Safety and Security Requirements

### ISSUE THREAD

**Issue by Wee-Ming** [RI0US04/P7-2-SIT-INF2001#26]
Task ID: #26

Task details: Confirmation of Safety and Security Requirements.

Goals of the task: Ensure that the Safety and Security Requirements are specified properly.

Success criteria: Only when the Safety and Security Requirements are confirmed.

Allocated time: 1 hour

Start date: 09 September 2023

End date: 09 September 2023

Priority: Medium

**Comment by Wee-Ming** [comment]
1. Work done in detail: 

Researched on Web Application best practices, identified input validation and sanitization requirements to prevent Cross-Site Scripting and SQL Injection attacks.

Identified password protection measures such as password complexity, encrypting passwords stored in databases, and password expiration requirements.

Identified employees maximum stipulated working hours in accordance to MOM labor laws, ensuring employees are not overworked leading to dangerous working conditions.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If security requirements documented are complex, more resources must be allocated towards development operations.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 9 September 2023
End Date: 9 September 2023

**Comment by RI0US04** [comment]
Reviewed HEHE

**Comment by chariseeyip** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed
