### ISSUE TITLE
M1 Report: Other Requirements

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#27]
Task ID: #27

Task details: Documenting down other requirements of our M1 project.

Goals of the task: Ensure proper documentation of other requirements of the M1 report.

Success criteria: When other requirements are documented.

Allocated time: 1 Hour

Start date: 11 September 2023

End date: 11 September 2023

Priority: High

**Comment by RI0US04** [comment]
1. Work done in detail: For this section, we have documented other requirements of our project regarding employee workload hours and PDPA.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: We need to be clear of the law regarding workload hours if not, there might be issues that arise during the implementation.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 11 September 2023
End Date: 11 September 2023

**Comment by erickmh859** [comment]
NFR23 Done

**Comment by RI0US04** [comment]
NFR24 Done

**Comment by erickmh859** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed
