### ISSUE TITLE
1.1.3 Confirm User Interface Requirements

### ISSUE THREAD

**Issue by Wee-Ming** [RI0US04/P7-2-SIT-INF2001#28]
Task ID: #28

Task details: Confirmation of the user interface requirements

Goals of the task: To review and confirm the user interface requirements such as the layout, accessibility and usability of the interface

Success criteria: When all the user interface requirements have been thoroughly reviewed and confirmed

Allocated time: 5 hours

Start date: 11 September 2023

End date: 12 September 2023

Priority: High

**Comment by Wee-Ming** [comment]
1. Work done in detail: For this section, we confirmed our user interface requirements of our project such as the layout, accessibility and usability of the interface.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without confirming, we cannot put into the M1 report.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 11 September 2023
End Date: 12 September 2023

**Comment by erickmh859** [comment]
UI1 Done

**Comment by RI0US04** [comment]
UI3 Done

**Comment by TARZH3N** [comment]
UI5 & UI7 Done

**Comment by lmaoggrofl** [comment]
UI4 Done

**Comment by Wee-Ming** [comment]
UI2 Done
