### ISSUE TITLE
M1 Report: User Interface Requirements

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#29]
Task ID: #29

Task details: Documenting down the User Interface Requirements in our report

Goals of the task: Ensuring that the confirm User Interface requirements is properly documented in our report

Success criteria: When the User Interface Requirements has been completed 

Allocated time:  1 hour

Start date: 11 September 2023

End date: 12 September 2023

Priority: Medium

**Comment by RI0US04** [comment]
1. Work done in detail: Proper documentation of the confirmed User Interface requirements in the report by putting them into a table for easy reading.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: NIL

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 11 September 2023
End Date: 12 September 2023

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed
