### ISSUE TITLE
#02 - Assign roles

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#3]
Task details: To assign various software engineering roles to the various members of the team

Goals of the task:  To ensure all members have a role and stay commited to the role.

Success criteria: When every member has a role in the software engineering team.

Allocated time: 15 minutes

Start date: 29 August 2023

End date: 29 August 2023

**Comment by Wee-Ming** [comment]
Completed 

Team Lead: Charisee Yip (@chariseeyip)
Tech Lead: Wilson (@lmaoggrofl)
Full Stack Developer: Aloysus Koh (@RI0US04)
Full Stack Developer: Zhen Yu (@TARZH3N)
QA Engineer: Wee Ming (@Wee-Ming)
UI/UX Designer: Eric Koh (@erickmh859)
