### ISSUE TITLE
1.1.4 Create System Architecture Diagram

### ISSUE THREAD

**Issue by Wee-Ming** [RI0US04/P7-2-SIT-INF2001#30]
Task ID: #30

Task details: Creation of the system architecture diagram

Goals of the task: Ensure that the System Architecture diagram is properly created.

Success criteria: Only when the system architecture diagram is successfully created.

Allocated time: 3 hours

Start date: 13 September 2023

End date: 13 September 2023

Priority: Medium

**Comment by Wee-Ming** [comment]
1. Work done in detail: Created the system architecture diagram based on the high level requirements of how the architecture of the system should be built.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without creation of the system architecture diagram, it would be hard for the team to visualize how the architecture of the system is to be built.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 13 September 2023
End Date: 13 September 2023

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed
