### ISSUE TITLE
M1 Report: Product Overview

### ISSUE THREAD

**Issue by TARZH3N** [RI0US04/P7-2-SIT-INF2001#31]
Task ID: #31

Task details: Documenting down the product overview of our M1 project

Goals of the task: Ensure proper documentation of our product overview of the M1 report

Success criteria: Once the product overview are documented

Allocated time: 4 hours

Start date: 13 September 2023

End date: 13 September 2023

Priority: High

**Comment by TARZH3N** [comment]
1. Work done in detail: For this section, we document our product overview of our project such as the system architecture of our system

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: The product overview consists of our system architecture. Without it, the client might not have the full picture on how the system works and it causes the M1 report to be incomplete

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 13 September 2023
End Date: 13 September 2023

**Comment by chariseeyip** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed
