### ISSUE TITLE
1.2.1 Create Use Case Model

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#33]
Task ID: #33

Task details: Creating the Use Case Model based on Functional Requirements.

Goals of the task: Ensure that the Use Case Model is correct according to the Functional Requirements.

Success criteria: Once the Use Case Model is confirmed.

Allocated time: 10 hours

Start date: 14 September 2023

End date: 15 September 2023

Priority: High

**Comment by chariseeyip** [comment]
1. Work done in detail: Ensure that all Functional Requirements are grouped and displayed into the Use Case Model.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the Use Case Model is not finalized, We cannot visualize the interaction between the actors and the system.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 14 September 2023
End Date: 15 September 2023

**Comment by chariseeyip** [comment]
Manager Actor Done

**Comment by TARZH3N** [comment]
Manager Actor Done

**Comment by lmaoggrofl** [comment]
Employee Actor Done

**Comment by Wee-Ming** [comment]
Employee Actor Done

**Comment by RI0US04** [comment]
IT Administrator Done
