### ISSUE TITLE
M1 Report: Use Case Model

### ISSUE THREAD

**Issue by TARZH3N** [RI0US04/P7-2-SIT-INF2001#34]
Task ID: #34

Task details: Documenting down the use case model for our M1 report

Goals of the task: Ensure proper documentation of our use case model of the M1 report

Success criteria: Once the use case model are documented

Allocated time: 4 hours

Start date: 18 September 2023

End date: 18 September 2023

Priority: High

**Comment by TARZH3N** [comment]
1. Work done in detail: For this section, we created our use case model by effectively grouping and summarizing all the functional use case for individual job roles


2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the Use Case Model is not finalized, We cannot visualize the interaction between the actors and the system and  it causes the M1 report to be incomplete

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 13 September 2023
End Date: 13 September 2023

**Comment by erickmh859** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed
