### ISSUE TITLE
M1 Report: Appendix A - Use Case Descriptions

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#36]
Task ID: #36

Task details: Documenting down the Use Case Description for our M1 report

Goals of the task: Ensure proper documentation of our Use Case Description of the M1 report

Success criteria: Once the Use Case Description are documented

Allocated time: 4 hours

Start date: 14 September 2023

End date: 14 September 2023

Priority: High

**Comment by chariseeyip** [comment]
1. Work done in detail: For this section, we finalize the Use Case Description then document into the M1 Report.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without documenting the Use Case Description into the M1 report, the planning and estimations will be delayed. 

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 14 September 2023
End Date: 14 September 2023

**Comment by RI0US04** [comment]
Reviewed 	| (• ◡•)|

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed
