### ISSUE TITLE
1.3.1.1 Calculate Size Estimation

### ISSUE THREAD

**Issue by erickmh859** [RI0US04/P7-2-SIT-INF2001#39]
Task ID: #39 

Task details: Calculate the total Use Case Points.

Goals of the task: Assess the size and complexity of a software project based on its use cases.

Success criteria: Get the result of product of Unadjusted Use Case Weight, Technical Complexity Factors and Environment Factor

Allocated time: 2 hours

Start date: 19 September 2023

End date: 19 September 2023

Priority: High

**Comment by erickmh859** [comment]
1. Work done in detail: Calculate the Unadjusted Use Case Weight, Technical Complexity Factors and Environment Factor.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If we don't calculate the estimation, we will not be able to get the hours estimation for the implementation, which will delay our timeline. 

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 19 September 2023
End Date: 19 September 2023

**Comment by lmaoggrofl** [comment]
Calculate Environment Factors (EF) - Done

**Comment by erickmh859** [comment]
Calculate the unadjusted weight of all actors - Done

**Comment by Wee-Ming** [comment]
Calculating the Technical Complexity Factors (TCF) - Done

**Comment by TARZH3N** [comment]
Calculate the unadjusted weight of all use cases - Done
