### ISSUE TITLE
M1 Report: Software Estimation

### ISSUE THREAD

**Issue by erickmh859** [RI0US04/P7-2-SIT-INF2001#41]
Task ID: #41

Task details: Documenting what our team has done for the software estimation

Goals of the task: Ensure that the documentation of software estimation is done correctly

Success criteria: Once the documentation of software software estimation is confirmed

Allocated time:  4 hours

Start date: 20 September 2023

End date: 20 September 2023

Priority: High

**Comment by erickmh859** [comment]
1. Work done in detail: For this task, we had to document our calculations for the size estimation using Total Unadjusted point (UUCW) * Technical Complexity Factor (TCF) * Environment Factor (EF) to derive the Use Case Point (UCP)

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the calculation is not done, our team cannot complete the task allocation for the gantt chart which leads to a delay in completion of the deadline

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 20 September 2023
End Date: 20 September 2023

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed
