### ISSUE TITLE
1.3.2.1 Create Work Breakdown Structure

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#43]
Task ID: #43 

Task details: Break down the work into an organized structure.

Goals of the task: Understand the overview of the workload management structure.

Success criteria: Finalized the Work Breakdown Structure.

Allocated time: 2 Hours

Start date: 20 September 2023

End date: 21 September 2023

Priority: High

**Comment by RI0US04** [comment]
1. Work done in detail: Break down the work into sections and sub sections.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If this is not done, it will be affect the visualization of the workload.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 20 September 2023
End Date: 21 September 2023

**Comment by chariseeyip** [comment]
2 Design Specification and Management - Done

**Comment by erickmh859** [comment]
1.3 Project Estimation and Planning - Done

**Comment by RI0US04** [comment]
1.1 Requirements Specification - Done

**Comment by lmaoggrofl** [comment]
1.2 Use Case Diagram and Description - Done

**Comment by Wee-Ming** [comment]
3 Implementation of Product - Done

**Comment by TARZH3N** [comment]
4 Testing - Done
