### ISSUE TITLE
1.3.2.2 Create Gantt Chart

### ISSUE THREAD

**Issue by TARZH3N** [RI0US04/P7-2-SIT-INF2001#44]
Task ID: #44 

Task details: Create and plan the schedule when each task is supposed to be completed.

Goals of the task: Proper documentation and allocation of each task.

Success criteria: Once the Gantt chart is completed.

Allocated time: 4 hours

Start date: 21 September 2023

End date: 22 September 2023

Priority: High

**Comment by TARZH3N** [comment]
1. Work done in detail: Document all tasks and allocate each task to a member with start and due date.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without a proper gantt chart, the task might be messy and may cause delay in the completion.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 21 September 2023
End Date: 22 September 2023

**Comment by chariseeyip** [comment]
M1 Planning - Done

**Comment by RI0US04** [comment]
M1 Planning - Done

**Comment by lmaoggrofl** [comment]
M3 Planning - Done

**Comment by Wee-Ming** [comment]
M3 planning done

**Comment by TARZH3N** [comment]
M2 Planning - Done

**Comment by erickmh859** [comment]
M2 Planning - Done
