### ISSUE TITLE
M1 Report: Project Management

### ISSUE THREAD

**Issue by lmaoggrofl** [RI0US04/P7-2-SIT-INF2001#45]
Task ID: #45 

Task details: Add the Project Management into the M1 Report.

Goals of the task: Finalized the Project Management.

Success criteria: Documenting the Project Management into the M1 Report.

Allocated time: 1 Hour

Start date: 22 September 2023

End date: 22 September 2023

Priority: High

**Comment by lmaoggrofl** [comment]
1. Work done in detail:  Add the documentation of work planning into M1 report.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without the project management, it will affect the timeline of the project. 

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 22 September 2023
End Date: 22 September 2023

**Comment by chariseeyip** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed
