### ISSUE TITLE
M1 Report: Choice of Methodology

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#46]
Task ID: #46

Task details: Document what our team’s SDLC methodology 

Goals of the task: To ensure that our SDLC is properly documented

Success criteria: Once the methodology is properly documented

Allocated time: 2 Hours

Start date: 21 September 2023

End date: 21 September 2023

Priority: Medium

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed
