### ISSUE TITLE
M1 Report: Appendix B - Data Dictionary

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#47]
Task ID: #47

Task details: Create and document the data dictionary to define all the keywords used.

Goals of the task: Define all the terms used in our report.

Success criteria: Once the keywords are properly defined.

Allocated time: 1 Hour

Start date: 22 September 2023

End date: 22 September 2023

Priority: Low

**Comment by chariseeyip** [comment]
1. Work done in detail:  Add all the definitions of keywords into the M1 report.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: NIL

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 22 September 2023
End Date: 22 September 2023

**Comment by chariseeyip** [comment]
Reviewed and Completed 16-18

**Comment by RI0US04** [comment]
Reviewed and Completed 1 -3

**Comment by Wee-Ming** [comment]
Reviewed and Completed 4-6

**Comment by erickmh859** [comment]
Review and Completed 13-15

**Comment by TARZH3N** [comment]
Reviewed and Defined 10 - 12
