### ISSUE TITLE
M2 Report: Product Scope Changes

### ISSUE THREAD

**Issue by TARZH3N** [RI0US04/P7-2-SIT-INF2001#49]
Task ID: #49

Task details: Make changes to the product scope of our project.

Goals of the task: Edit and finalize the scope of the product.

Success criteria: When the product scope has been successfully edited and documented in the report.

Allocated time: 2 Hour

Start date: 25 September 2023

End date: 25 September 2023

Priority: High

**Comment by TARZH3N** [comment]
1. Work done in detail: Make changes to the product scope by editing the scope and boundaries of the software, its purpose and benefits of the software.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the product scope is not documented down, the report would not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 25 September 2023
End Date: 25 September 2023

**Comment by erickmh859** [comment]
reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed
