### ISSUE TITLE
Schedule Client Meeting

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#5]
Task ID: #05

Task details: To schedule the client meeting with Professor Quah Chee Kwang

Goals of the task: To interview Prof Quah as part of our requirement elicitation 

Success criteria: Professor Quah attends the meeting and we get the information which we need

Allocated time: 05 Minutes

Start date: 31 August 2023

End date: 31 August 2023

Priority: High

**Comment by erickmh859** [comment]
1. Work done in detail: All members decided on which date they are available on in the google sheets provided

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If not scheduled, we would not know task requirements

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 31 August 2023
End Date: 31 August 2023
