### ISSUE TITLE
M2 Report: References and Acknowledgements

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#50]
Task ID: #50

Task details: Make changes to the reference and acknowledgement of our project.

Goals of the task: Edit the references and acknowledgement of the product.

Success criteria: When the reference and acknowledgement have been successfully edited and documented in the report.

Allocated time: 1 Hour

Start date: 25 September 2023

End date: 25 September 2023

Priority: High

**Comment by RI0US04** [comment]
1. Work done in detail: Make changes to the reference and acknowledge section

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the reference and acknowledgement are not documented, the report will not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 25 September 2023
End Date: 25 September 2023

**Comment by TARZH3N** [comment]
Reviewed.

**Comment by erickmh859** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed
