### ISSUE TITLE
M2 Report: Changes in Requirements

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#51]
Task ID: #51

Task details: Make changes to the requirements in our M2 report

Goals of the task: Ensure the changes in requirements are correctly reflected in the M2 report 

Success criteria: When the change in requirements has been edited and documented in the M2 report.

Allocated time: 2 Hour

Start date: 25 September 2023

End date: 25 September 2023

Priority: Medium

**Comment by chariseeyip** [comment]
1. Work done in detail: The team has made the changes necessary to the requirements in the M2 report

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If not changed, then the M2 report will not be correct which means that we would need more time to change it later

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 25 September 2023
End Date: 25 September 2023

**Comment by TARZH3N** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed
