### ISSUE TITLE
M2 Report: Updated Use Case Descriptions

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#52]
Task ID: #52

Task details: Make changes to Use Case Descriptions.

Goals of the task: Edit and finalize the Use Case Descriptions.

Success criteria: When the Use Case Descriptions have been successfully edited and documented in the report.

Allocated time: 5 hours

Start date: 27 September 2023

End date: 27 September 2023

Priority: High

**Comment by chariseeyip** [comment]
1. Work done in detail: Make changes to the Use Case Descriptions by editing scenarios and editing the flow.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the Use Case Descriptions are not finalized, the flow of the system will be unclear.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 27 September 2023
End Date: 27 September 2023

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed
