### ISSUE TITLE
2.2 Detailed Design

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#53]
Task ID: #53

Task details: Create the class, and sequence diagram for the M2 Report

Goals of the task: Ensure that the class and sequence diagram are completed

Success criteria: Completion of the class and sequence diagram

Allocated time: 52 hours

Start date: 28 September 2023

End date: 20 October 2023

Priority: High

**Comment by lmaoggrofl** [comment]
1. Work done in detail: Class and Sequence Diagram created and written down in the M2 report

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the creation of the class and sequence diagram is not completed, the system flow might be unclear which hinders the progression and completion of other dependent diagrams and tasks, ultimately delaying the completion of the project.


4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 28 September 2023
End Date: 20 October 2023
