### ISSUE TITLE
2.2.1 Design Class Diagram

### ISSUE THREAD

**Issue by Wee-Ming** [RI0US04/P7-2-SIT-INF2001#54]
Task ID: #54

Task details: Craft the Class Diagram

Goals of the task: Craft and finalize the Design Component Diagram.

Success criteria: Completion of the Class Diagram

Allocated time: 12 hours

Start date: 28 September 2023

End date: 20 October 2023

Priority: High

**Comment by lmaoggrofl** [comment]
1. Work done in detail: Make changes to the Use Case Descriptions by editing. Continually revise the Class Diagram with any modifications made to the Sequence Diagram, ensuring both diagrams are consistently aligned and reflect the most recent design decisions.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the Class Diagram is not properly and steadfastly documented, it will disrupt the subsequent development of the Sequence Diagram. Such a disruption can create a bottleneck, hindering the timely progression and completion of other dependent diagrams and tasks.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 28 September 2023
End Date: 20 October 2023
