### ISSUE TITLE
M2 Report: Class Diagram

### ISSUE THREAD

**Issue by Wee-Ming** [RI0US04/P7-2-SIT-INF2001#55]
Task ID: #55

Task details: Document the Class Diagram

Goals of the task: Ensure that the Class Diagram is properly documented.

Success criteria: Once the Class Diagram is properly documented

Allocated time: 2 hours

Start date: 21 October 2023

End date: 21 October 2023

Priority: High

**Comment by lmaoggrofl** [comment]
1. Work done in detail: In this section, we documented the class diagram by explaining the classes.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without the documentation, the M2 report will be incomplete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 21 October 2023
End Date: 21 October 2023

**Comment by erickmh859** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed
