### ISSUE TITLE
2.2.2 Design Sequence Diagram

### ISSUE THREAD

**Issue by lmaoggrofl** [RI0US04/P7-2-SIT-INF2001#56]
#56 2.2.2 Design Sequence Diagram

Task ID: #56

Task details: Craft the Sequence Diagram 

Goals of the task: Craft and finalize the Sequence Diagram.

Success criteria: Completion of the Sequence Diagram and approved by all members

Allocated time: 40 hours

Start date: 5 October 2023

End date: 20 October 2023

Priority: High

**Comment by TARZH3N** [comment]
1. Work done in detail: Ensure the Sequence Diagram is well crafted and within the scope.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without the Sequence Diagram, system flow might be unclear and delay the completion of the project.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 5 October 2023

End Date: 20 October 2023
