### ISSUE TITLE
2.2.2.1 Sequence Diagram for Allocate Job to Employee

### ISSUE THREAD

**Issue by lmaoggrofl** [RI0US04/P7-2-SIT-INF2001#57]
Task ID: #57

Task details: Craft the design of Sequence Diagram for Allocate Job To Employee.

Goals of the task: Craft and finalize the design of Sequence Diagram for Allocate Job To Employee.

Success criteria: Completion of the Sequence Diagram for Allocate Job To Employee and approved by all members

Allocated time: 20 hours

Start date: 5 October 2023

End date: 12 October 2023

Priority: High

**Comment by chariseeyip** [comment]
1. Work done in detail: Ensure that the Sequence Diagram for Allocate Job To Employee is well crafted by reviewing flow of the diagram.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the Sequence Diagram for Allocate Job To Employee is not well crafted, it may cause misunderstanding of the system.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 12 October 2023
End Date: 20 October 2023
