### ISSUE TITLE
2.2.2.2 Sequence Diagram for Submit Availability

### ISSUE THREAD

**Issue by lmaoggrofl** [RI0US04/P7-2-SIT-INF2001#58]
Task ID: #58

Task details: Craft the Sequence Diagram for Submit Availability

Goals of the task: Craft and finalize the Sequence Diagram for Submit Availability.

Success criteria: Completion of the Sequence Diagram for Submit Availability and approved by all members.

Allocated time: 20 hours

Start date: 13 October 2023

End date: 20 October 2023

Priority: High

**Comment by erickmh859** [comment]
1. Work done in detail: Ensure the Sequence Diagram is well crafted for Submit Availability and within the scope.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without the Sequence Diagram for Submit Availability, system flow might be unclear and delay the completion of the project.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 20 October 2023
End Date: 27 October 2023
