### ISSUE TITLE
M2 Report: Sequence Diagram

### ISSUE THREAD

**Issue by TARZH3N** [RI0US04/P7-2-SIT-INF2001#59]
Task ID: #59

Task details: Documenting down the Sequence Diagram in the M2 report.

Goals of the task: Ensure proper documentation of our Sequence Diagram in the M2 report.

Success criteria: Once the Sequence Diagram are documented

Allocated time: 2 Hours

Start date: 20 October 2023

End date: 20 October 2023

Priority: High

**Comment by TARZH3N** [comment]
1. Work done in detail: Documented the flow of the sequence diagram.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the sequence diagram is not documented down, the report would not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 20 October 2023
End Date: 20 October 2023

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed
