### ISSUE TITLE
Conduct Client Meeting

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#6]
Task ID: #6

Task details: Conduct the meeting with the client based on the questions we have generated to elicit requirements.

Goals of the task: To successfully conduct the client meeting

Success criteria: When the client meeting gets conducted successfully

Allocated time: 15 minutes

Start date: 07 September 2023

End date: 07 September 2023

Priority: High

**Comment by TARZH3N** [comment]
1. Work done in detail: Conducted the client meeting on the scheduled date and time, and asked questions to elicit requirements from client

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If client meeting is not conducted, we cannot elicit requirements.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 07 September 2023
End Date: 07 September 2023
