### ISSUE TITLE
2.3 Architectural Design

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#60]
Task ID: #60

Task details: Craft the Architectural design.

Goals of the task: Craft and finalize the Architectural design.

Success criteria: Completion of the Architectural design and approved by all members

Allocated time: 12 hours

Start date: 23 October 2023

End date: 27 October 2023

Priority: High

**Comment by RI0US04** [comment]
1. Work done in detail: Ensure the architectural design is well crafted and within the scope.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Without the architectural design, system flow might be unclear and delay the completion of the project.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 23 October 2023
End Date: 27 October 2023
