### ISSUE TITLE
2.3.1 Design Component Diagram

### ISSUE THREAD

**Issue by erickmh859** [RI0US04/P7-2-SIT-INF2001#61]
Task ID: #61

Task details: Craft the design Component Diagram.

Goals of the task: Craft and finalize the design Component Diagram.

Success criteria: Completion of the design Component Diagram and approved by all members

Allocated time: 5 hours

Start date: 23 October 2023

End date: 27 October 2023

Priority: High

**Comment by Wee-Ming** [comment]
1. Work done in detail: Ensure that the Component Diagram is well crafted by reviewing the major components and their relationship.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the Component Diagram is not well crafted, it may cause misinterpretations of the system.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 23 October 2023
End Date: 27 October 2023
