### ISSUE TITLE
M2 Report: Component Diagram

### ISSUE THREAD

**Issue by TARZH3N** [RI0US04/P7-2-SIT-INF2001#62]
Task ID: #62

Task details: Documenting down the Component Diagram of our M2 project.

Goals of the task: Ensure proper documentation of the component diagram of the M2 report

Success criteria: Once the component diagram is documented

Allocated time: 2 hours

Start date: 27 October 2023

End date: 27 October 2023

Priority: High

**Comment by Wee-Ming** [comment]
1. Work done in detail: For this section, we have document component diagram of our project such as the Job, User and Availability Management

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: The component diagram displays how the component uses the interface to interact with each other, if this is not documented, the report will not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 27 October 2023
End Date: 27 October 2023

**Comment by TARZH3N** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed
