### ISSUE TITLE
M2 Report: Updated Project Plan

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#63]
Task ID: #63

Task details: Update and document the Project Plan in the M2 report.

Goals of the task: Ensure proper documentation of the updated Project Plan in the M2 report.

Success criteria: Once the updated Project Plan are documented

Allocated time: 2 Hour

Start date: 27 October 2023

End date: 27 October 2023

**Comment by RI0US04** [comment]
1. Work done in detail: Documented the updated Project Plan.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the project plan is not updated, the hours allocated might be unclear.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 27 October 2023
End Date: 27 October 2023

**Comment by chariseeyip** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed
