### ISSUE TITLE
M2 Report: Data Dictionary

### ISSUE THREAD

**Issue by erickmh859** [RI0US04/P7-2-SIT-INF2001#64]
Task details: Create and document the data dictionary to define all the keywords used.

Goals of the task: Define all the terms used in our report.

Success criteria: Once the keywords are properly defined.

Allocated time: 1 Hour

Start date: 27 October 2023

End date: 27 October 2023

Priority: Low

**Comment by erickmh859** [comment]
1. Work done in detail: Add all the definitions of keywords into the M2 report.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: NIL

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 27 October 2023
End Date: 27 October 2023

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed
