### ISSUE TITLE
M3 Report: References and Acknowledgments

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#68]
Task ID: #68

Task details: Documenting down the references and acknowledgement for the report.

Goals of the task: Ensure proper references and acknowledgements are complete.

Success criteria: Once the references and acknowledgements are completed.

Allocated time: 2 hours

Start date: 27 October 2023

End date: 27 October 2023

Priority: High

**Comment by chariseeyip** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed.

**Comment by TARZH3N** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed
