### ISSUE TITLE
Create Meeting Minutes

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#7]
Task ID: #07

Task details: To create post interview meeting minutes

Goals of the task: To compile and collate the meeting minutes after the interview based on the meeting

Success criteria: Once we fully transcribe the meeting minutes from the interview with the client

Allocated time: 2 Hours

Start date: 07 September 2023

End date: 08 September 2023

Priority: Medium

**Comment by Wee-Ming** [comment]
1. Work done in detail: Meeting minutes are being transcribed from the recording of the interview with Prof Quah, which is our client. 


2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: Should meeting minutes not be compiled, the team would need to keep backtracking to the recording to listen, which hinders the process of the project.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 07 September 2023
End Date: 08 September 2023
