### ISSUE TITLE
M3 Report: Architecture Design

### ISSUE THREAD

**Issue by Wee-Ming** [RI0US04/P7-2-SIT-INF2001#71]
Task ID: #71

Task details: Document what our team has done for the Architecture Design

Goals of the task: Ensure that the Architecture Design is properly documented

Success criteria: Once the Architecture Design has been documented 

Allocated time: 2 hours

Start date: 30 October 2023

End date: 30 October 2023

Priority: High

**Comment by Wee-Ming** [comment]
1. Work done in detail: Document what we have done for Architecture Design

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the architecture design is not documented, the report will not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 30/10/2023


End Date: 30/10/2023

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed
