### ISSUE TITLE
3.2.1 Factory Design Pattern

### ISSUE THREAD

**Issue by RI0US04** [RI0US04/P7-2-SIT-INF2001#73]
Task ID: #73

Task details: To implement factory design patterns into our current project.

Goals of the task: To ensure that the factory design pattern is added to our project, by redesigning our class diagram to enforce factory design pattern principles.

Success criteria: Once the correct implementation of the factory design pattern is done

Allocated time: 3 Hours

Start date: 31 October 2023

End date: 31 October 2023

Priority: High

**Comment by RI0US04** [comment]
1. Work done in detail: Developed factory classes to create and manage objects without specifying the exact classes of objects that will be created.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the factory design pattern is not done, the project will be incomplete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 31 October 2023

End Date: 31 October 2023

**Comment by TARZH3N** [comment]
Reviewed
