### ISSUE TITLE
M3 Report: Detailed Design

### ISSUE THREAD

**Issue by erickmh859** [RI0US04/P7-2-SIT-INF2001#75]
Task ID: #75

Task details: Document what our team has done for the detailed design

Goals of the task: Ensure that the detailed design is properly documented

Success criteria: Once the detailed design has been documented 

Allocated time: 3 Hours

Start date: 01 November 2023

End date: 01 November 2023

Priority: High

**Comment by erickmh859** [comment]
1. Work done in detail: Documenting what we have done for detailed design

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the detailed design is not documented, the report will not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 01 November 2023


End Date: 01 November 2023

**Comment by RI0US04** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed
