### ISSUE TITLE
Analyze Requirements

### ISSUE THREAD

**Issue by TARZH3N** [RI0US04/P7-2-SIT-INF2001#8]
Task ID: #8

Task details: Analyze the requirements that we have elicited from the client, based on the generated meeting minutes.

Goals of the task: To analyze the requirements that we have gathered

Success criteria: When the requirements have been fully analyzed

Allocated time: 3 hours

Start date: 07 September 2023

End date: 08 September 2023

Priority: High

**Comment by erickmh859** [comment]
1. Work done in detail: Thoroughly analyze the requirements we have gathered through the client meeting, draw out the specific requirements of the product.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If requirements are not analyzed, we cannot have a good understanding of the client’s needs.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 07 September 2023
End Date: 08 September 2023
