### ISSUE TITLE
M3 Report: Project Prototype and Wireframes

### ISSUE THREAD

**Issue by chariseeyip** [RI0US04/P7-2-SIT-INF2001#93]
Task ID: #93

Task details: Document what our team has done for the project prototype and wireframes

Goals of the task: Ensure that the project prototype and wireframes is properly documented

Success criteria: Once the project prototype and wireframes has been documented 

Allocated time: 5 hours

Start date: 21 November 2023

End date: 21 November 2023

Priority: High

**Comment by chariseeyip** [comment]
1. Work done in detail: Documenting what we have done for project prototype and wireframes

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the project prototype and wireframes are not documented, the report will not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 21 November 2023
End Date: 21 November 2023

**Comment by chariseeyip** [comment]
Did the following:
4.2.8 Delete Job Service Request
4.2.9 View Unallocated / Allocated Jobs
4.2.10 Manual Job Allocation
4.2.11 Automatic Job Allocation
4.2.12 Reallocate Job

**Comment by erickmh859** [comment]
I did the following:
4.2.4 View Job Schedule
4.2.5 View Job Service Requests
4.2.6 Add Job Service Request	
4.2.7 Update Job Service

**Comment by RI0US04** [comment]
I did the following:
4.1 Login Functionality
4.2.1 Navigation Bar
4.2.2 Manager Landing Page 
4.2.3 View Employee Availability

**Comment by Wee-Ming** [comment]
I did the following:
4.4.3 View Employees    
4.4.4 Add Employee    
4.4.5 Update Employee Details    
4.4.6 Delete Employee    
4.4.7 Profile

**Comment by lmaoggrofl** [comment]
I did the following:
4.2.13 View Employee Unavailability Notice 
4.2.14 Profile   
4.3.1 Navigation Bar  
4.3.2 Employee Landing Page 
4.3.3 View Employee Schedule

**Comment by erickmh859** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed
