### ISSUE TITLE
M3 Report: Black-box Testing

### ISSUE THREAD

**Issue by lmaoggrofl** [RI0US04/P7-2-SIT-INF2001#95]
Task ID: #95

Task details: Document what our team has done for the black-box testing

Goals of the task: Ensure that the black-box testing is properly documented

Success criteria: Once the black-box testing has been documented 

Allocated time: 2 Hours

Start date: 22 November 2023

End date: 22 November 2023

Priority: High

**Comment by lmaoggrofl** [comment]
1. Work done in detail: Documenting what we have done for black-box testing; our decision making table and rationale behind employing it.

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the black-box testing is not documented, the report will not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 22 November 2023
End Date: 22 November 2023

**Comment by chariseeyip** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by erickmh859** [comment]
Reviewed
