### ISSUE TITLE
M3 Report: White-box Testing

### ISSUE THREAD

**Issue by TARZH3N** [RI0US04/P7-2-SIT-INF2001#97]
Task ID: #97

Task details: Document what our team has done for the white-box testing

Goals of the task: Ensure that the white-box testing is properly documented

Success criteria: Once the white-box testing has been documented 

Allocated time: 2 Hours

Start date: 23 November 2023

End date: 23 November 2023

Priority: High

**Comment by TARZH3N** [comment]
1. Work done in detail: Documenting what we have done for white-box testing

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the white-box testing is not documented, the report will not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 23 November 2023
End Date: 23 November 2023

**Comment by erickmh859** [comment]
Reviewed

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed
