### ISSUE TITLE
M3 Report: Project Management

### ISSUE THREAD

**Issue by erickmh859** [RI0US04/P7-2-SIT-INF2001#99]
Task ID: #99

Task details: Document what our team has done for the project management

Goals of the task: Ensure that the project management is properly documented

Success criteria: Once the project management has been documented 

Allocated time: 2 hours

Start date: 24 November 2023

End date: 24 November 2023

Priority: High

**Comment by erickmh859** [comment]
1. Work done in detail: Documenting what we have done for project management

2. Has this work been committed to the repo? NIL

3. How does the work affect the completion deadline: If the project management is not documented, the report will not be complete.

4. Are there any changes to the success or completion criteria of the task? No

5. Start Date: 24 November 2023
    End Date:24 November 2023

**Comment by Wee-Ming** [comment]
Reviewed

**Comment by lmaoggrofl** [comment]
Reviewed

**Comment by chariseeyip** [comment]
Reviewed

**Comment by TARZH3N** [comment]
Reviewed

**Comment by RI0US04** [comment]
Reviewed
